name: Publish Allure Report Action
description: Generate selenium report for the allure tool and send latest data.

inputs:
  project_name:
    description: "This refers to the name of the project that goes in allure testing tool."
    required: false
    type: string
    default: "${{ github.event.repository.name }}"
  results_path:
    description: "Path of the test results directory, relative to the test_suite_path. Defaults to test-results."
    required: false
    type: string
    default: "test-results"

secrets:
  QA_REPORT_TOOL_ADMIN_PASSWORD:
    required: true
    description: "password"
  QA_REPORT_TOOL_ADMIN_USERNAME:
    required: true
    description: "username"

runs:
  using: 'node16'
  main: 'dist/index.js'
