name: Publish Allure Report Action
description: Generate selenium report for the allure tool and send latest data.

inputs:
  project_name:
    description: "This refers to the name of the project that goes in allure testing tool."
    required: false
    type: string
    default: "${{ github.event.repository.name }}"
  results_path:
    description: "Path of the test results directory, relative to the test_suite_path. Defaults to test-results."
    required: false
    type: string
    default: "test-results"
  username:
    description: "Username for QA tool of admin"
    required: true
  password:
    description: "Password for QA tool of admin"
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
